// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.28;

import { ResourceTokenRegistryBase } from "../../Base.t.sol";
import {
  IResourceTokenRegistryErrors,
  IResourceTokenRegistryEvents
} from "../../../src/interfaces/IResourceTokenRegistry.sol";
import { Defaults } from "../../helpers/Defaults.sol";

contract Mint_Test is ResourceTokenRegistryBase {
  function test_RevertIf_CallerIsNotMinter() public {
    vm.prank(unauthorized);
    vm.expectRevert(IResourceTokenRegistryErrors.NotAuthorizedMinter.selector);
    registry.mint(alice, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);
  }

  function test_RevertIf_InvalidTokenType_Zero() public {
    vm.prank(minter);
    vm.expectRevert(abi.encodeWithSelector(IResourceTokenRegistryErrors.InvalidTokenType.selector, uint8(0x00)));
    registry.mint(alice, 0x00, Defaults.DEFAULT_METADATA);
  }

  function test_RevertIf_InvalidTokenType_Four() public {
    vm.prank(minter);
    vm.expectRevert(abi.encodeWithSelector(IResourceTokenRegistryErrors.InvalidTokenType.selector, uint8(0x04)));
    registry.mint(alice, 0x04, Defaults.DEFAULT_METADATA);
  }

  function test_MintFreshToken_ReturnsAutoGeneratedId() public {
    vm.prank(minter);
    uint256 id = registry.mint(alice, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);

    // First permission token: (1 << 8) | 0x01
    assertEq(id, Defaults.PERMISSION_TOKEN_ID);
  }

  function test_MintFreshToken_SetsBalance() public {
    uint256 id = _mintDefault(alice, Defaults.PERMISSION_TYPE);
    assertEq(registry.balanceOf(alice, id), 1);
  }

  function test_MintFreshToken_SetsCreator() public {
    uint256 id = _mintDefault(alice, Defaults.PERMISSION_TYPE);
    assertEq(registry.creator(id), minter);
  }

  function test_MintFreshToken_StoresMetadata() public {
    uint256 id = _mintDefault(alice, Defaults.PERMISSION_TYPE);
    assertEq(registry.tokenMetadata(id), Defaults.DEFAULT_METADATA);
  }

  function test_MintFreshToken_EmitsTokenCreatedEvent() public {
    vm.prank(minter);
    vm.expectEmit(true, true, false, true);
    emit IResourceTokenRegistryEvents.TokenCreated(
      Defaults.PERMISSION_TOKEN_ID, minter, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA
    );
    registry.mint(alice, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);
  }

  function test_MintFreshToken_EmitsTransferEvent() public {
    vm.prank(minter);
    vm.expectEmit(true, true, true, true);
    emit IResourceTokenRegistryEvents.Transfer(minter, address(0), alice, Defaults.PERMISSION_TOKEN_ID, 1);
    registry.mint(alice, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);
  }

  function test_MintMultipleTokens_IncrementsId() public {
    vm.startPrank(minter);
    uint256 id1 = registry.mint(alice, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);
    uint256 id2 = registry.mint(bob, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);
    vm.stopPrank();

    // First: (1 << 8) | 0x01, Second: (2 << 8) | 0x01
    assertEq(id1, (uint256(1) << 8) | 0x01);
    assertEq(id2, (uint256(2) << 8) | 0x01);
    assertFalse(id1 == id2);
  }

  function test_MintDifferentTypes_IndependentCounters() public {
    vm.startPrank(minter);
    uint256 permId = registry.mint(alice, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);
    uint256 respId = registry.mint(alice, Defaults.RESPONSIBILITY_TYPE, Defaults.DEFAULT_METADATA);
    uint256 dirId = registry.mint(alice, Defaults.DIRECTIVE_TYPE, Defaults.DEFAULT_METADATA);
    vm.stopPrank();

    assertEq(permId, (uint256(1) << 8) | 0x01);
    assertEq(respId, (uint256(1) << 8) | 0x02);
    assertEq(dirId, (uint256(1) << 8) | 0x03);
  }

  function test_LastId_ReturnsCounterForType() public {
    assertEq(registry.lastId(Defaults.PERMISSION_TYPE), 0);

    _mintDefault(alice, Defaults.PERMISSION_TYPE);
    assertEq(registry.lastId(Defaults.PERMISSION_TYPE), 1);

    _mintDefault(bob, Defaults.PERMISSION_TYPE);
    assertEq(registry.lastId(Defaults.PERMISSION_TYPE), 2);

    // Other types unaffected
    assertEq(registry.lastId(Defaults.RESPONSIBILITY_TYPE), 0);
  }

  function testFuzz_MintToVariousAddresses(address to) public {
    vm.assume(to != address(0));

    vm.prank(minter);
    uint256 id = registry.mint(to, Defaults.PERMISSION_TYPE, Defaults.DEFAULT_METADATA);

    assertEq(registry.balanceOf(to, id), 1);
  }

  function testFuzz_MintAllValidTypes(uint8 tokenType) public {
    vm.assume(tokenType >= 0x01 && tokenType <= 0x03);

    vm.prank(minter);
    uint256 id = registry.mint(alice, tokenType, Defaults.DEFAULT_METADATA);

    assertEq(registry.balanceOf(alice, id), 1);
    assertEq(registry.tokenType(id), tokenType);
  }
}
