// SPDX-License-Identifier: MIT
pragma solidity >=0.8.28;

/// @title TZTypes
/// @notice Trust Zone protocol-level types. Defines the full parameter surface of a trust zone.
library TZTypes {
  /// @notice Sentinel value for hat IDs unknown at compile time.
  /// @dev Replaced with the actual agreement hat ID during setup.
  uint256 internal constant HAT_ID_SENTINEL = type(uint256).max;
  /// @notice The parameter dimensions of a trust zone boundary and domain.
  /// @dev Not all types are implemented as onchain mechanisms. Some are expressed as resource tokens,
  ///      some are expressed through eligibility requirements, and some are post-hackathon.
  /// @dev Ordered so Permission=1, Responsibility=2, Directive=3 match resource token type prefixes (0x01/0x02/0x03).
  enum TZParamType {
    Constraint, // 0 — hard, self-enforcing rules (→ ERC-7579 hooks)
    Permission, // 1 (0x01) — access to resources (→ resource token)
    Responsibility, // 2 (0x02) — obligations (→ resource token)
    Directive, // 3 (0x03) — behavioral rules (→ resource token)
    Eligibility, // 4 — requirements to enter the zone (→ Hats eligibility modules)
    Reward, // 5 — positive incentives for good behavior (→ claimable mechanism)
    Penalty, // 6 — negative incentives for bad behavior (→ claimable mechanism)
    PrincipalAlignment, // 7 — incentive alignment with principal (→ Eligibility requirement)
    DecisionModel // 8 — internal composition: 1-of-n, m-of-n (→ Eligibility requirement)
  }

  /// @notice The deployment/activation strategy for a mechanism module.
  enum TZModuleKind {
    HatsModule, // 0 — deploy via HatsModuleFactory; wire to hat if Eligibility/Penalty
    ERC7579Hook, // 1 — pre-deployed singleton; onInstall via executeFromExecutor
    External // 2 — pre-deployed; module.call(data) during activation if data non-empty
  }

  /// @notice A mechanism attached to a trust zone. Used for negotiation terms,
  ///         activation config, and runtime claim/adjudication routing.
  /// @dev Only Constraint, Eligibility, Reward, and Penalty appear as deployed mechanisms.
  ///      Directive, Responsibility, and Permission are represented as resource tokens.
  ///      PrincipalAlignment and DecisionModel are expressed through Eligibility mechanisms.
  /// forge-lint: disable-next-item(pascal-case-struct)
  struct TZMechanism {
    TZParamType paramType;
    TZModuleKind moduleKind;
    address module;
    bytes data;
  }

  /// @notice A resource token to mint to a trust zone's TZ account on activation.
  /// @dev Token ID is auto-generated by the ResourceTokenRegistry. Metadata is immutable.
  /// forge-lint: disable-next-item(pascal-case-struct)
  struct TZResourceTokenConfig {
    TZParamType tokenType; // Permission (0x01), Responsibility (0x02), Directive (0x03)
    bytes metadata; // creation data, ABI-encoded, set on mint
  }

  /// @notice Configuration for a single trust zone within an agreement.
  /// forge-lint: disable-next-item(pascal-case-struct)
  struct TZConfig {
    address party;
    uint256 agentId; // ERC-8004 agent identity (0 = no 8004, e.g. human party)
    uint32 hatMaxSupply;
    string hatDetails;
    TZMechanism[] mechanisms;
    TZResourceTokenConfig[] resources;
  }
}
